import { FaReact, FaNodeJs, FaGitAlt, FaAws } from "react-icons/fa";
import {
  SiNextdotjs,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiSqlite,
  SiFirebase,
  SiTypescript,
  SiTailwindcss,
  SiMui,
  SiAntdesign,
  SiJsonwebtokens,
  SiAuth0,
  SiAxios,
  SiReactquery,
  SiGraphql,
  SiGooglecloud,
  SiNginx,
  SiPm2,
} from "react-icons/si";

export const personalInfo = {
  name: "Md Alamin Faraji",
  role: "Web Application Developer",
  phone: "+8801518420973",
  email: "alaminice1617@gmail.com",
  location: "Narail, Bangladesh",
  about:
    "I am a Web Application Developer from Bangladesh with extensive experience in web development. I specialize in creating attractive, fully responsive websites with a focus on user interface and branding. My expertise extends to cloud platforms like AWS, GCP, and deployment tools such as Nginx and PM2.",
  skills: [
    { name: "React.js", percentage: 90, icon: FaReact },
    { name: "Next.js", percentage: 85, icon: SiNextdotjs },
    { name: "Node.js", percentage: 85, icon: FaNodeJs },
    { name: "Express.js", percentage: 85, icon: SiExpress },
    { name: "MongoDB", percentage: 80, icon: SiMongodb },
    { name: "PostgreSQL", percentage: 75, icon: SiPostgresql },
    { name: "MySQL", percentage: 75, icon: SiMysql },
    { name: "SQLite", percentage: 70, icon: SiSqlite },
    { name: "Firebase", percentage: 80, icon: SiFirebase },
    { name: "TypeScript", percentage: 85, icon: SiTypescript },
    { name: "Tailwind CSS", percentage: 95, icon: SiTailwindcss },
    { name: "Material UI", percentage: 85, icon: SiMui },
    { name: "Ant Design", percentage: 80, icon: SiAntdesign },
    { name: "JWT", percentage: 90, icon: SiJsonwebtokens },
    { name: "NextAuth.js", percentage: 85, icon: SiAuth0 },
    { name: "Axios", percentage: 90, icon: SiAxios },
    { name: "Tanstack Query", percentage: 85, icon: SiReactquery },
    { name: "GraphQL", percentage: 75, icon: SiGraphql },
    { name: "AWS", percentage: 70, icon: FaAws },
    { name: "GCP", percentage: 70, icon: SiGooglecloud },
    { name: "Nginx", percentage: 75, icon: SiNginx },
    { name: "PM2", percentage: 80, icon: SiPm2 },
    { name: "Git", percentage: 90, icon: FaGitAlt },
  ],
};

export const projects = [
  {
    id: 1,
    title: "The Luxury Brand Cleaning Services ",
    description:
      "Raptor The Luxury Brand, a premier Canadian cleaning services platform offering a wide range of services like window cleaning, interior/exterior cleaning, gutter maintenance, and high-rise cleaning.",
    tech: [
      "Next.js",
      "Material UI",
      "Express",
      "Node.js",
      "MySQL",
      "Redux",
      "JWT",
      "NextAuth.js",
      "stripe",
      "Google map API",
      "Hostinger VPS Server",
    ],
    image: "/raptor-logo-squre.jpg",
    liveUrl: "https://www.raptorscleaning.com/",
    features: [
      "Responsive Design",
      "Stripe Integration",
      "Google Map API",
      "Users can request quotes for services",
      "Track updates on service requests",
      "View team details, including photos of assigned teams",
      "Access invoices and other service-related information",
      "Payment Integration: Seamless payment processing using Stripe",
      "Service Pages: Detailed views of the company's offerings to help users understand and choose the services they need",
      "Optimized for accessibility and SEO",
    ],
    isGithubPrivate: true,
    githubUrlClient: "https://github.com/AlaminFaraji/raptors-cleaning",
    githubUrlServer: "https://github.com/AlaminFaraji/raptors-cleaning-server",
  },
  {
    id: 2,
    title: "PIF Capital",
    description:
      "PIF Capital has been dedicated to helping small and medium enterprises navigate the complexities of capital markets, operational scaling, and corporatisation.",
    tech: [
      "Next.js",
      "tailwind css",
      "shadcn",
      "Strapi CMS",
      "stripe",
      "Node.js",
      "PostgreSQL",
      "JWT",
      "Graphql",
      "zustand",
      "React pdf/renderer",
    ],
    image: "/logo.webp",
    features: [
      "Responsive Design",
      "Stripe Integration",
      "Developed a comprehensive booking page that handles fetching event data, managing referral codes, and processing payments using Zustand for state management.",
      "Implemented referral code validation and discount calculations, including real-time updates and error handling for invalid codes.",
      "Built a secure payment handling system with terms and conditions validation, payment processing, and redirection to a success page upon completion.",
      "Designed a dynamic Purchase History component with filtering options, pagination, and invoice management, allowing users to download invoices as PDFs.",
      "Integrated third-party libraries such as @react-pdf/renderer for PDF generation, dayjs for date manipulation, and Zustand for state management.",
      "Optimized user experience by providing real-time feedback on payment status, event progress, and referral code applications with a clean and responsive UI.",
    ],
    liveUrl: "https://client.pifcapital.sg/events",
    isGithubPrivate: true,
    githubUrlClient: "https://github.com/AlaminFaraji/pif-capital",
    githubUrlServer: "https://github.com/AlaminFaraji/pif-capital-server",
  },
  {
    id: 3,
    title: "YouthMedia24",
    description:
      "YouthMedia24 is a dynamic news portal dedicated to empowering the younger generation with the latest news on innovations and emerging technologies. Our mission is to keep young minds informed and inspired by sharing insightful stories, groundbreaking advancements, and up-to-date technology trends",
    tech: [
      "Next.js",
      "strapi cms",
      "Mui",
      "Zustand",
      "GraphQL",
      "Firebase",
      "GCP",
    ],
    image: "/youthMedia24.png",
    features: [
      "Developed a comprehensive news platform, YouthMedia24, targeting the younger generation with a focus on innovations and updated technology.",
      "Implemented user authentication and role-based access control for Regular Users, Admins, and Super Admins using JWT/OAuth.",
      "Built dynamic dashboards for different user roles to manage submissions, approvals, and analytics efficiently.",
      "Integrated rich media support for articles, allowing users to upload images, videos, and audio files seamlessly.",
      "Designed a mobile-responsive and user-friendly UI using Next.js and Tailwind CSS for an optimal browsing experience.",
      "Leveraged Strapi CMS for backend management and Zustand for state management to handle articles, comments, and user data efficiently.",
    ],
    liveUrl: "https://youth-media24-fe.vercel.app/bangla",
    isGithubPrivate: false,
    githubUrlClient: "https://github.com/mdalaminfaraji/youthMedia24-fe",
    githubUrlServer: "https://github.com/mdalaminfaraji/youth-media-24-be",
  },
];

export const experiences = [
  {
    company: "NexStack, Singapore",
    position: "Nextjs React Developer",
    period: "Jun 2024 - Feb 2025",
    responsibilities: [
      "Team Leader of Bangladesh Branch",
      "Developed responsive web applications",
      "Assisted Backend Development with Strapi CMS",
      "Mentored junior developers",
      "Gain knowledge of cloud platforms like AWS, GCP, and deployment tools such as Nginx and PM2",
      "Implemented CI/CD pipelines",
    ],
  },
  {
    company: "Raptor The Luxury Brand, Canada",
    position: "Frontend Developer",
    period: "July 2023 - June 2024",
    responsibilities: [
      "Developed responsive web applications",
      "Collaborated with design team",
      "Optimized application performance",
      "Integrated with payment gateway (Stripe)",
      "Implemented secure authentication and authorization",
      "Google map integration",
    ],
  },
];
